<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Http\Resources\MissingValue;

class UserResource extends JsonResource
{
    public $with = ['data1' => ['f']];

    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
//        return parent::toArray($request);
//        dd($request->with);
//        dd(new articleResource($this->articles));
        return  [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'type'=>$this->when($this->id===1,'admin'),
            'article'=>$this->whenLoaded('articles',function () use($request){

                return $request->with==='articles' ? articleResource::collection($this->articles) : new MissingValue();
            })
//            'article'=>new articleResource($this->articles)),
//            $this->mergeWhen($this->id===1,['type'=>'admin']),
        ];
//        if ($request->with === 'articles') {
//            $data['article'] = $this->articles;
//        }
//        return $data;
    }

//    public function with($request)
//    {
//    return parent::with([]); // TODO: Change the autogenerated stub
//        return ['relation' => ['articles' => $this->articles]];
//    }
}
